export const myNestedVals = {
	'1': {
		KARNATAKA: [
			('BANGALORE': {
				'address': 'asd'
			}),
			'GULBARGA',
			'DAKSHINA KARNATAKA',
			'MYSORE',
			'HASSAN',
			'MANGALORE',
			'DAVANGERE',
			'BELAGAVI'
		],
		ANDRAPRADESH: [ 'ANANTHAPURA', 'VISHAKAPATNAM' ],
		ASSAM: [ 'GUWAHATI' ],
		PUNJAB: [ 'CHANDIGRAH', 'JALANDHAR' ],
		DELHI: [ 'NEW DELHI' ],
		'UTTAR PRADESH': [ 'KANPUR' ],
		CHATTISGARH: [ 'BHILAI', 'RAIPUR' ],
		GUJARAT: [ 'SURAT', 'AHMEDABAD', 'VADODARA', 'RAJKOT', 'DAHOD' ],
		KERALA: [ 'KOCHI', 'CALICUT', 'MALLAPURAM', 'KASARAGOD', 'ERANAKULAM', 'THRISSUR', 'KANNUR', 'KOTHAMANGALAM' ],
		'WEST BENGAL': [ 'KOLKATTA' ],
		MAHARASTRA: [
			'NAGPUR',
			'KOLHAPUR',
			'THANE',
			'AKOLA',
			'PUNE',
			'MUMBAI',
			'DHULE',
			'SOLAPUR',
			'AMRAVATI',
			'NASIK',
			'PARBHANI',
			'JALNA'
		],
		'MADHYA PRADESH': [ 'CHHINDWARA', 'VIDISHA', 'INDORE' ],
		MANIPUR: [ 'IMPHAL' ],
		ORISSA: [ 'KORAPUT', 'BERHAMPUR', 'BHUBANESWAR', 'BARGARH', 'SAMBALPUR' ],
		RAJASTHAN: [ 'AJMER', 'JAIPUR' ],
		TELANGANA: [ 'HYDERABAD' ],
		TAMILNADU: [ 'CHENNAI', 'COIMBATORE', 'MADURAI', 'ERODE', 'TIRUNELVELI', 'TRICHY', 'PONDICHERRY', 'TIRUPUR' ],
		HARYANA: [ 'FARIDABAD' ],
		GURGAON: [ 'GURUGRAM' ],
		JHARKAND: [ 'RANCHI' ]
	},
	'2': {
		GHANA: [ 'CITY1', 'CITY2', 'CITY3' ],
		'SOUTH AFRICA': [ 'CITY1', 'CITY2', 'CITY3' ]
	},
	'3': {
		BERLIN: [ 'CITY1', 'CITY2', 'CITY3' ],
		BAVARIA: [ 'CITY1', 'CITY2', 'CITY3' ]
	}
};
